### ISSUE TITLE
Change the Comple Matrix algebra to use a external implementation

### ISSUE THREAD

**Issue by dmoranj** [dmoranj/qbitos#17]
The current implementation of all the Complex Matrix Algebra was meant to practice with the mathematical foundations of Quantum Computing, but it's now the time to change it to a more efficient one (as the implementation of Shor's algorithm is stalled due to computation time issues). There are not so many complex matrix libraries out there that can be integrated with clojure, but Java has some good candidadates.

A good starting point may be: http://www.ee.ucl.ac.uk/~mflanaga/java/index.html

**Comment by logc** [comment]
I was about to open an issue exactly like this one. A search in https://clojars.org showed me these hits:
- https://clojars.org/complex/complex
- https://clojars.org/com.gfredericks/z
- https://clojars.org/number-theory/number-theory

**Comment by dmoranj** [comment]
The problem is not to support complex numbers, but to give a full support of complex matrix operations, and, most importantly, an optimized one. All the needed operations are already implemented in qbitos, the problem here is efficiency, and some operations that may be useful and are not yet implemented. Take a look at [Flanagan's page for complex matrices](http://www.ee.ucl.ac.uk/~mflanaga/java/ComplexMatrix.html). I did some research a couple of weeks ago in order to find any library that supported complex matrices for Clojure, but it doesn't seem to be any sound candidate. There are some implementations, but I would rather use a well documented, full-featured Java library than a timid Clojure prototype (everyone praise Java Interop!).

**Comment by dmoranj** [comment]
I changed my mind and started to test [JBlas](http://jblas.org/).

The first try can be found in the branch task/changeMatrixImplementation  if you want to give it a try. I hope to have it completely migrated this weekend, so I can test whether it solves the efficiency problems or not.
